import React from 'react'
import Card from '../../../Global/Card/Card'

export default function CastList() {
    return (
        <>
            <div class="cast-list d-flex overflow-auto gap-3 py-3">
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Actor\n200x250"
                    header="Actor"
                    character="Character"
                    className="cast-member"
                    alt="Actor"
                />
            </div>
        </>
    );
}
