import React from 'react'
import Card from '../../../Global/Card/Card'

export default function MovieList() {
    return (
        <>
            <div className="movie-list d-flex overflow-auto gap-3 px-2 py-3">
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
                <Card
                    src="https://placehold.co/200x250/FFFFFF/000000?text=Movie\n"
                    header="Movie"
                    className="movie"
                    alt="Movie"
                    badge="PG-13"
                    year="2023"
                    genre="Action"
                />
            </div>
        </>
    )
}
